-- EMPLOYEES1 테이블 생성 
CREATE TABLE employees1 (
	EMP_NO INT(11)
	,BITRT_DATE DATE NOT NULL
	,FIRST_NAME VARCHAR(14) NOT NULL
	,LAST_NAME VARCHAR(16) NOT NULL
	,GENDER ENUM('M','F') NOT NULL
	,HIRE_DATE DATE NOT NULL
	,CONSTRAINT PK_EMPLOYEES1_EMP_NO PRIMARY KEY(EMP_NO)
);

-- SALARIES1 테이블 생성 
CREATE TABLE salaries1 (
	EMP_NO INT(11)
	,SALARY INT(11) NOT NULL
	,FROM_DATE DATE 
	,TO_DATE DATE NOT NULL
	,CONSTRAINT PK_SALARIES1 PRIMARY KEY(EMP_NO,FROM_DATE)
);

	-- 테이블에 참조키 설정, INDEX 추가
	ALTER TABLE salaries1 ADD FOREIGN KEY(EMP_NO) REFERENCES employees1(EMP_NO);
	ALTER TABLE salaries1 ADD INDEX EMP_NO(EMP_NO);

-- TITLES1 테이블 생성 
CREATE TABLE titles1 (
	EMP_NO INT(11)
	,TITLE VARCHAR(50)
	,FROM_DATE DATE
	,TO_DATE DATE
	,CONSTRAINT PK_TITLES1 PRIMARY KEY(EMP_NO,TITLE,FROM_DATE)
);
	-- 테이블에 참조키 설정, INDEX 추가 
	ALTER TABLE TITLES1 ADD FOREIGN KEY(EMP_NO) REFERENCES employees1(EMP_NO)
	ALTER TABLE TITLES1 ADD INDEX EMP_NO(EMP_NO);

-- DEPT_EMP1 테이블 생성 
CREATE TABLE dept_emp1 (
	EMP_NO INT(11)
	,DEPT_NO CHAR(4)
	,FROM_DATE DATE NOT NULL
	,TO_DATE DATE NOT NULL
	,CONSTRAINT PK_DEPT_EMP1 PRIMARY KEY(EMP_NO,DEPT_NO)
);
	-- 테이블에 참조키 설정, INDEX 추가 
	ALTER TABLE DEPT_EMP1 ADD FOREIGN KEY(EMP_NO) REFERENCES employees1(EMP_NO)
	ALTER TABLE DEPT_EMP1 ADD INDEX EMP_NO(EMP_NO)
	ALTER TABLE DEPT_EMP1 ADD INDEX DEPT_NO(DEPT_NO);

-- DEPARTMENTS 테이블 생성
CREATE TABLE departments1 (
	DEPT_NO CHAR(4)
	,DEPT_NAME VARCHAR(40) NOT NULL
	,CONSTRAINT PK_DEPARTMENTS PRIMARY KEY(DEPT_NO)
);

SELECT *
FROM departments1;